# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2016 CERN.
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

notifications:
  email: false

sudo: false

language: node_js

node_js:
  - '0.10'
  - '0.12'
  - '4.0.0'
  - '4.1.2'
  - '4.2.2'
  - '5.0.0'
  - '5.1.0'
  - '5.2.0'
  - '5.3.0'
  - '5.4.0'

before_script:
  - 'npm install -g gulp'

before_install:
  - 'npm i'

script:
  - 'npm test'

after_success:
  - 'npm run-script coverage'

before_deploy:
  - 'npm run-script build'

deploy:
  provider: npm
  skip_cleanup: true
  email: info@invenio-software.org
  api_key:
    secure: upp/8nZSEOVNtR89THu+Hz9OjoUH2jOI0pvH//YVZZ/e3DUVLqW9Qm4Cn7DGUNt2vsv3H7tvR6anC+Y9jaubZVbFnONSoPcS/WK1mLR/FnuXHGO4XOGLVOhTkn7/xPVOtePbkwyHOEDXJ0seK2j94AEkQeMeEfx1hHwtEGUGNWUcMZthQc6HPdtSI01nADdvLJ78vPERwUifIaGGBqnfOgTYq1pHK6Qc8ptuNlQZDUdDv79RCSpMCibOh8gT5HTRhDC8p8noPT5zl4AmvycCyLMZ03l6DBF2W4TbK8IrzdKtHjWUGS/dc6PD02OK9FGD2oI+W69PMwUlOvHlltiK+vOQUju7WwjkXcb1nXjNL01cXnAscezTtvQKGA8SuMu3JWN4KRnfO2v2e+Rhtrq5AumjUc19jpBNAKFQbzFmzyTm4q2lmLMnCXhLR/tLNBfe0jsF89L0ZBRbZ18ScCUC3jmZdpRED7H5irgwrGcPFNivRoubgOkoqbDFS/9Kd8X2ynMQjCu3GkQ4GZvZzIIBt5u5Fo+rh5ao3en9xBpxRou3vSqiy/EHfD5psG7WVevcd0QlTAGW2Bqm7pN6EgR3RBD/sU33R9eKYx7rqyBk4kqaQOF/4zPisnIJVRao09PsgPzKy8acz/5HKuGzQXjH8UGmKLoxGmChaLkcHKCsiGI=
  on:
    tags: true
    repo: inveniosoftware/invenio-csl-js
    branch: master
    node: '5.1.0'
